// <auto-generated />
using System;
using CsApp.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CsApp.Migrations
{
    [DbContext(typeof(CsAppDBContext))]
    [Migration("20260721130150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CsApp.DB.Models.Files", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Files", "public");
                });

            modelBuilder.Entity("CsApp.DB.Models.Results", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("avg_execution_time")
                        .HasColumnType("numeric");

                    b.Property<decimal>("avg_value")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("delta_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_file")
                        .HasColumnType("integer");

                    b.Property<decimal>("max_value")
                        .HasColumnType("numeric");

                    b.Property<decimal>("median_value")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("min_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("min_value")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("Results", "public");
                });

            modelBuilder.Entity("CsApp.DB.Models.Values", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("execution_time")
                        .HasColumnType("integer");

                    b.Property<int>("id_file")
                        .HasColumnType("integer");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("Values", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
